name: hydrofield
description: Offline-first field data collection app for hydrologic surveys.
version: 0.1.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  uuid: ^3.0.7
  sqflite: ^2.2.5
  path_provider: ^2.0.15
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
